// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LunarEclipse.Controls {
    
    
    public partial class AnimationTimelineWidget {
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LunarEclipse.Controls.AnimationTimelineWidget
            Stetic.BinContainer.Attach(this);
            this.WidthRequest = 800;
            this.HeightRequest = 70;
            this.Name = "LunarEclipse.Controls.AnimationTimelineWidget";
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
