// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LunarEclipse {
    
    
    public partial class Properties {
        
        private Gtk.VBox vboxProperties;
        
        private Gtk.Table tableNameType;
        
        private Gtk.Label lblName;
        
        private Gtk.Label lblType;
        
        private Gtk.Entry ObjectName;
        
        private Gtk.Entry ObjectType;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget LunarEclipse.Properties
            Stetic.BinContainer.Attach(this);
            this.Name = "LunarEclipse.Properties";
            // Container child LunarEclipse.Properties.Gtk.Container+ContainerChild
            this.vboxProperties = new Gtk.VBox();
            this.vboxProperties.Name = "vboxProperties";
            this.vboxProperties.Spacing = 6;
            // Container child vboxProperties.Gtk.Box+BoxChild
            this.tableNameType = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.tableNameType.Name = "tableNameType";
            this.tableNameType.RowSpacing = ((uint)(6));
            this.tableNameType.ColumnSpacing = ((uint)(6));
            // Container child tableNameType.Gtk.Table+TableChild
            this.lblName = new Gtk.Label();
            this.lblName.Name = "lblName";
            this.lblName.Xalign = 1F;
            this.lblName.LabelProp = Mono.Unix.Catalog.GetString("Name");
            this.tableNameType.Add(this.lblName);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.tableNameType[this.lblName]));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child tableNameType.Gtk.Table+TableChild
            this.lblType = new Gtk.Label();
            this.lblType.Name = "lblType";
            this.lblType.Xalign = 1F;
            this.lblType.LabelProp = Mono.Unix.Catalog.GetString("Type");
            this.tableNameType.Add(this.lblType);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.tableNameType[this.lblType]));
            w2.TopAttach = ((uint)(1));
            w2.BottomAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child tableNameType.Gtk.Table+TableChild
            this.ObjectName = new Gtk.Entry();
            this.ObjectName.CanFocus = true;
            this.ObjectName.Name = "ObjectName";
            this.ObjectName.Text = Mono.Unix.Catalog.GetString("<No Name>");
            this.ObjectName.IsEditable = true;
            this.ObjectName.InvisibleChar = '●';
            this.tableNameType.Add(this.ObjectName);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.tableNameType[this.ObjectName]));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child tableNameType.Gtk.Table+TableChild
            this.ObjectType = new Gtk.Entry();
            this.ObjectType.CanFocus = true;
            this.ObjectType.Name = "ObjectType";
            this.ObjectType.Text = Mono.Unix.Catalog.GetString("Canvas");
            this.ObjectType.IsEditable = false;
            this.ObjectType.InvisibleChar = '●';
            this.tableNameType.Add(this.ObjectType);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.tableNameType[this.ObjectType]));
            w4.TopAttach = ((uint)(1));
            w4.BottomAttach = ((uint)(2));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            this.vboxProperties.Add(this.tableNameType);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vboxProperties[this.tableNameType]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            this.Add(this.vboxProperties);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
