// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LunarEclipse {
    
    
    public partial class PropertyGroup {
        
        private Gtk.Expander expander;
        
        private Gtk.Label PropertyGroupLabel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget LunarEclipse.PropertyGroup
            Stetic.BinContainer.Attach(this);
            this.Name = "LunarEclipse.PropertyGroup";
            // Container child LunarEclipse.PropertyGroup.Gtk.Container+ContainerChild
            this.expander = new Gtk.Expander(null);
            this.expander.CanFocus = true;
            this.expander.Name = "expander";
            this.PropertyGroupLabel = new Gtk.Label();
            this.PropertyGroupLabel.Name = "PropertyGroupLabel";
            this.PropertyGroupLabel.LabelProp = Mono.Unix.Catalog.GetString("<b>PropertyGroupLabel</b>");
            this.PropertyGroupLabel.UseMarkup = true;
            this.expander.LabelWidget = this.PropertyGroupLabel;
            this.Add(this.expander);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
